Repository EVerest/libocpp, pull requests merged in 2024-02, with the labels that each got.

#443 Fixed reconnect attempt, fixed sys error on timer dtor
  include/ocpp/common/websocket/websocket_tls_tpm.hpp
  lib/ocpp/common/websocket/websocket_tls_tpm.cpp
Labels: bug

#448 Number of fixes to the Metervalue implementation for 2.0.1
  config/v201/component_schemas/custom/Connector_1_1.json
  config/v201/component_schemas/custom/Connector_2_1.json
  config/v201/component_schemas/custom/EVSE_1.json
  config/v201/component_schemas/custom/EVSE_2.json
  config/v201/component_schemas/standardized/AlignedDataCtrlr.json
  config/v201/component_schemas/standardized/AuthCacheCtrlr.json
  config/v201/component_schemas/standardized/AuthCtrlr.json
  config/v201/component_schemas/standardized/InternalCtrlr.json
  config/v201/component_schemas/standardized/LocalAuthListCtrlr.json
  config/v201/component_schemas/standardized/OCPPCommCtrlr.json
  config/v201/component_schemas/standardized/ReservationCtrlr.json
  config/v201/component_schemas/standardized/SampledDataCtrlr.json
  config/v201/component_schemas/standardized/SecurityCtrlr.json
  config/v201/component_schemas/standardized/TxCtrlr.json
  config/v201/config.json
  include/ocpp/common/aligned_timer.hpp
  include/ocpp/v201/ctrlr_component_variables.hpp
  include/ocpp/v201/transaction.hpp
  include/ocpp/v201/utils.hpp
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/ctrlr_component_variables.cpp
  lib/ocpp/v201/evse.cpp
  lib/ocpp/v201/utils.cpp
Labels: OCPP2.0.1

#476 Support for AuthCacheDisablePostAuthorize and DisableRemoteAuthorization
  include/ocpp/v201/ctrlr_component_variables.hpp
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/ctrlr_component_variables.cpp
Labels: enhancement, OCPP2.0.1
