Repository EVerest/libocpp, pull requests merged in 2025-02, with the labels that each got.

#961 Move meter values functions and callbacks to functional block
  include/ocpp/v201/charge_point.hpp
  include/ocpp/v201/functional_blocks/meter_values.hpp
  lib/CMakeLists.txt
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/functional_blocks/meter_values.cpp
Labels: OCPP2.0.1

#968 Move diagnostics handlers and callbacks to functional block.
  include/ocpp/v201/charge_point.hpp
  include/ocpp/v201/functional_blocks/diagnostics.hpp
  include/ocpp/v201/monitoring_updater.hpp
  lib/CMakeLists.txt
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/functional_blocks/diagnostics.cpp
  lib/ocpp/v201/monitoring_updater.cpp
Labels: OCPP2.1

#984 Fix bug where security event notification was sent while bootnotification was still pending.
  include/ocpp/common/message_queue.hpp
Labels: include-in-release

#966 Catch exception when assiging String<> type with too long string
  include/ocpp/common/cistring.hpp
  include/ocpp/common/string.hpp
  lib/ocpp/v201/charge_point.cpp
Labels: include-in-release

#932 Implemented code generator for EVerest yaml types from OCPP JSON Schemas
  src/code_generator/README.md
  src/code_generator/common/generate_cpp.py
  src/code_generator/common/generate_everest_types.py
  src/code_generator/common/templates/everest_type.yaml.jinja
  src/code_generator/common/utils.py
Labels: OCPP2.1

#1001 Start websocket ping timer when websocket connects
  config/v16/config-docker.json
  lib/ocpp/common/websocket/websocket_libwebsockets.cpp
Labels: include-in-release

#998 Only change state to available if the current state is 'Reserved'
  include/ocpp/v16/charge_point_state_machine.hpp
  lib/ocpp/v16/charge_point_impl.cpp
  lib/ocpp/v16/charge_point_state_machine.cpp
Labels: bug, include-in-release
