Repository EVerest/libocpp, pull requests merged in 2025-04, with the labels that each got.

#1007 Session cost add message
  doc/common/california_pricing_requirements.md
  include/ocpp/common/types.hpp
  include/ocpp/v16/charge_point.hpp
  include/ocpp/v16/charge_point_impl.hpp
  include/ocpp/v2/charge_point_callbacks.hpp
  include/ocpp/v2/functional_blocks/tariff_and_cost.hpp
  lib/ocpp/v16/charge_point.cpp
  lib/ocpp/v16/charge_point_impl.cpp
  lib/ocpp/v2/charge_point.cpp
  lib/ocpp/v2/functional_blocks/tariff_and_cost.cpp
Labels: OCPP2.0.1

#1035 DataTransfer.req(GetInstalledCertificates) NotFound
  lib/ocpp/v16/charge_point_impl.cpp
Labels: bug

#1038 Fixed bug to set CentralContractValidationAllowed
  lib/ocpp/v16/charge_point_configuration.cpp
Labels: bug

#1040 Bounds checks for Plug&Charge configuration keys
  config/v16/config-full.json
  config/v16/profile_schemas/Internal.json
  lib/ocpp/v16/charge_point_configuration.cpp
Labels: OCPP1.6

#1044 Fixed potential bad function call for set_connection_timeout_callback
  lib/ocpp/v16/charge_point_impl.cpp
Labels: bug

#1030 OCPP1.6 Message queue initialization
  lib/ocpp/v16/charge_point_impl.cpp
Labels: bug

#1034 Contract validation using V2G root
  lib/ocpp/v16/charge_point_impl.cpp
  lib/ocpp/v2/functional_blocks/authorization.cpp
  tests/lib/ocpp/v2/functional_blocks/test_authorization.cpp
Labels: bug

#1027 Integrate everest-sqlite as sqlite wrapper
  CMakeLists.txt
  dependencies.yaml
  doc/common/database_migrations.md
  include/ocpp/common/database/database_connection.hpp
  include/ocpp/common/database/database_exceptions.hpp
  include/ocpp/common/database/database_handler_common.hpp
  include/ocpp/common/database/database_schema_updater.hpp
  include/ocpp/common/database/sqlite_statement.hpp
  include/ocpp/common/message_queue.hpp
  include/ocpp/v16/database_handler.hpp
  include/ocpp/v2/database_handler.hpp
  include/ocpp/v2/device_model_storage_sqlite.hpp
  include/ocpp/v2/init_device_model_db.hpp
  lib/CMakeLists.txt
  lib/ocpp/common/database/database_connection.cpp
  lib/ocpp/common/database/database_handler_common.cpp
  lib/ocpp/common/database/database_schema_updater.cpp
  lib/ocpp/common/database/sqlite_statement.cpp
  lib/ocpp/v16/charge_point_impl.cpp
  lib/ocpp/v16/database_handler.cpp
  lib/ocpp/v16/smart_charging.cpp
  lib/ocpp/v2/charge_point.cpp
  lib/ocpp/v2/component_state_manager.cpp
  lib/ocpp/v2/connector.cpp
  lib/ocpp/v2/database_handler.cpp
  lib/ocpp/v2/device_model.cpp
  lib/ocpp/v2/device_model_storage_sqlite.cpp
  lib/ocpp/v2/evse.cpp
  lib/ocpp/v2/functional_blocks/authorization.cpp
  lib/ocpp/v2/functional_blocks/diagnostics.cpp
  lib/ocpp/v2/functional_blocks/smart_charging.cpp
  lib/ocpp/v2/functional_blocks/transaction.cpp
  lib/ocpp/v2/init_device_model_db.cpp
  lib/ocpp/v2/transaction.cpp
  tests/lib/ocpp/common/CMakeLists.txt
  tests/lib/ocpp/common/database_testing_utils.hpp
  tests/lib/ocpp/common/test_database_migration_files.cpp
  tests/lib/ocpp/common/test_database_migration_files.hpp
  tests/lib/ocpp/common/test_database_schema_updater.cpp
  tests/lib/ocpp/v16/database_handler_mock.hpp
  tests/lib/ocpp/v16/database_stub.hpp
  tests/lib/ocpp/v16/database_tests.cpp
  tests/lib/ocpp/v16/profile_testsB.cpp
  tests/lib/ocpp/v16/test_composite_schedule.cpp
  tests/lib/ocpp/v16/test_database_migration_files.cpp
  tests/lib/ocpp/v16/test_smart_charging_handler.cpp
  tests/lib/ocpp/v2/device_model_test_helper.cpp
  tests/lib/ocpp/v2/device_model_test_helper.hpp
  tests/lib/ocpp/v2/functional_blocks/test_authorization.cpp
  tests/lib/ocpp/v2/functional_blocks/test_reservation.cpp
  tests/lib/ocpp/v2/functional_blocks/test_smart_charging.cpp
  tests/lib/ocpp/v2/mocks/database_handler_fake.hpp
  tests/lib/ocpp/v2/mocks/database_handler_mock.hpp
  tests/lib/ocpp/v2/smart_charging_test_utils.cpp
  tests/lib/ocpp/v2/test_charge_point.cpp
  tests/lib/ocpp/v2/test_component_state_manager.cpp
  tests/lib/ocpp/v2/test_database_handler.cpp
  tests/lib/ocpp/v2/test_database_migration_files.cpp
  tests/lib/ocpp/v2/test_init_device_model_db.cpp
  tests/libocpp-unittests.cmake
Labels: include-in-release
