Repository EVerest/libocpp, pull requests merged in 2025-03, with the labels that each got.

#1006 UnlockConnector refactoring
  CMakeLists.txt
  include/ocpp/v16/charge_point.hpp
  include/ocpp/v16/charge_point_impl.hpp
  lib/ocpp/v16/charge_point.cpp
  lib/ocpp/v16/charge_point_impl.cpp
  src/charge_point.cpp
Labels: OCPP1.6

#1018 Message handling hardening of OCPP1.6
  lib/ocpp/v16/charge_point_impl.cpp
Labels: bug, OCPP1.6

#1017 StopTransactionIfUnlockNotSupported configuration key
  config/v16/profile_schemas/Internal.json
  include/ocpp/v16/charge_point_configuration.hpp
  lib/ocpp/v16/charge_point_configuration.cpp
  lib/ocpp/v16/charge_point_impl.cpp
Labels: enhancement, OCPP1.6

#1016 Respond with to ChangeAvailability with Scheduled when in Preparing state
  include/ocpp/v16/charge_point_impl.hpp
  lib/ocpp/v16/charge_point_impl.cpp
Labels: bug, OCPP1.6

#1015 fix(Ocpp16): Make StopTransactionOnEVSideDisconnect optional
  config/v16/config-docker-tls.json
  config/v16/config-docker.json
  config/v16/profile_schemas/Core.json
  include/ocpp/v16/charge_point_configuration.hpp
  lib/ocpp/v16/charge_point_configuration.cpp
Labels: bug, OCPP1.6, errata

#1025 Reserved -> Occupied transition in OCPP2.0.1
  lib/ocpp/v2/charge_point.cpp
Labels: OCPP2.0.1
