Repository EVerest/libocpp, pull requests merged in 2025-01, with the labels that each got.

#923 Make supported OCPP protocol version configurable (v201, v21)
  config/v201/component_config/standardized/InternalCtrlr.json
  include/ocpp/v201/charge_point.hpp
  include/ocpp/v201/charge_point_callbacks.hpp
  include/ocpp/v201/connectivity_manager.hpp
  include/ocpp/v201/ctrlr_component_variables.hpp
  include/ocpp/v201/utils.hpp
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/connectivity_manager.cpp
  lib/ocpp/v201/ctrlr_component_variables.cpp
  lib/ocpp/v201/utils.cpp
Labels: OCPP2.0.1, OCPP2.1

#924 Check supported_feature_profiles for CostAndPrice before attempt to retrieve configuration key
  lib/ocpp/v16/charge_point_configuration.cpp
Labels: OCPP1.6, cpr

#950 Move 'Availability' callbacks and handlers to new functional block
  include/ocpp/v201/charge_point.hpp
  include/ocpp/v201/evse.hpp
  include/ocpp/v201/evse_manager.hpp
  include/ocpp/v201/functional_blocks/availability.hpp
  lib/CMakeLists.txt
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/evse.cpp
  lib/ocpp/v201/evse_manager.cpp
  lib/ocpp/v201/functional_blocks/availability.cpp
  tests/CMakeLists.txt
  tests/lib/ocpp/v201/mocks/evse_manager_fake.hpp
  tests/lib/ocpp/v201/mocks/evse_mock.hpp
Labels: OCPP2.0.1

#956 Implemented missing handle_message in display message functional block
  lib/ocpp/v201/functional_blocks/display_message.cpp
Labels: bug, OCPP2.0.1

#959 Move certificate stuff of iso15118 to security functional block.
  include/ocpp/v201/charge_point.hpp
  include/ocpp/v201/functional_blocks/security.hpp
  lib/ocpp/v201/charge_point.cpp
  lib/ocpp/v201/functional_blocks/security.cpp
  tests/lib/ocpp/v201/functional_blocks/CMakeLists.txt
Labels: OCPP2.0.1
